#!/usr/bin/env python3
"""Builds ui_emoji_data.c: every single-codepoint Twemoji and every flag, scaled to PX x PX,
as LVGL RGB565A8 images (an RGB565 plane, then an alpha plane).

ui_emoji.c turns the table into fonts the text fonts fall back to, so an emoji
in a message, a name or a preview draws in colour. Multi-codepoint sequences
(ZWJ families, skin tones) have no shaping in LVGL: they draw as their parts,
a toned hand untoned. Flags are the exception: each is stored under a private
codepoint, FLAG_BASE + letter1 * 26 + letter2, and UITask.cpp swaps a pair of
regional indicator letters for it before the text reaches a label.

Twemoji graphics: (c) Twitter / X and other contributors, CC-BY 4.0
(https://github.com/jdecked/twemoji).

Usage: emoji.py <twemoji assets/72x72 dir> <out.c>   (needs Pillow)
Called by generate.sh.
"""
import os
import sys
from PIL import Image

PX = 16
FLAG_BASE = 0xF0000   # Supplementary Private Use Area-A
RI_A = 0x1F1E6        # regional indicator symbol letter A


def codepoints(src):
    """(codepoint, file) of every glyph, sorted."""
    cps = []
    for f in os.listdir(src):
        name, ext = os.path.splitext(f)
        if ext != ".png":
            continue
        parts = [int(x, 16) for x in name.split("-")]
        if len(parts) == 2 and all(RI_A <= p < RI_A + 26 for p in parts):   # a flag
            cps.append((FLAG_BASE + (parts[0] - RI_A) * 26 + parts[1] - RI_A, f))
            continue
        if len(parts) > 1:
            continue
        cp = parts[0]
        # below U+2000 the text fonts already have it (digits, (c), (r)); the
        # skin tone swatches only ever follow another emoji: ui_emoji.c drops them
        if cp < 0x2000 or 0x1F3FB <= cp <= 0x1F3FF:
            continue
        cps.append((cp, f))
    return sorted(cps)


def main(src, out):
    glyphs = codepoints(src)
    cps = [cp for cp, _ in glyphs]
    data = bytearray()
    for _, f in glyphs:
        im = Image.open(os.path.join(src, f)).convert("RGBA")
        im = im.resize((PX, PX), Image.LANCZOS)   # Pillow premultiplies RGBA while resampling
        rgb, alpha = bytearray(), bytearray()
        raw = im.tobytes()
        for i in range(0, len(raw), 4):
            r, g, b, a = raw[i:i + 4]
            v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
            rgb += bytes((v & 0xFF, v >> 8))
            alpha.append(a)
        data += rgb + alpha

    n = len(cps)
    size = PX * PX * 3
    with open(out, "w") as o:
        o.write("/* Generated by emoji.py from Twemoji 15.1 (CC-BY 4.0) -- do not edit. */\n")
        o.write('#include "lvgl.h"\n\n')
        o.write("const uint16_t ui_emoji_count = %d;\n\n" % n)
        o.write("const uint32_t ui_emoji_cps[%d] = {\n" % n)
        for i in range(0, n, 8):
            o.write("  " + ", ".join("0x%X" % c for c in cps[i:i + 8]) + ",\n")
        o.write("};\n\n")
        o.write("static const uint8_t px[%d] = {\n" % len(data))
        for i in range(0, len(data), 24):
            o.write("  " + ",".join("0x%02X" % b for b in data[i:i + 24]) + ",\n")
        o.write("};\n\n")
        o.write("#define E(i) { .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565A8, "
                ".w = %d, .h = %d, .stride = %d }, .data_size = %d, .data = px + (i) * %d }\n"
                % (PX, PX, PX * 2, size, size))
        o.write("const lv_image_dsc_t ui_emoji_img[%d] = {\n" % n)
        for i in range(0, n, 10):
            o.write("  " + ", ".join("E(%d)" % j for j in range(i, min(n, i + 10))) + ",\n")
        o.write("};\n")
    print("emoji: %d glyphs, %d KB" % (n, len(data) // 1024))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
